#
# Copyright © 2017-2021 Samuel Holland <samuel@sholland.org>
# SPDX-License-Identifier: GPL-2.0-only
#

bin-y += check_counter check_timer

check_counter-objs := check_counter.o smp.o
check_timer-objs := check_timer.o smp.o
